---

- import_tasks: consul.yml

- import_tasks: configure.yml

- import_tasks: configure-others.yml
  tags: others

- import_tasks: configure-bootstrap.yml
  tags: bootstrap

- import_tasks: configure-others.yml
  when:
    - etcd == "false"
    - master == "false"
    - node == "true"

- import_tasks: copy-cert.yml

- import_tasks: disable-autoscaler.yml
  tags: others
  when:
    - automium_autoscaler_kubeconfig != ""

- import_tasks: disable-kubernetes-dashboard.yml
  tags: others
  when:
    - master == "true" or node == "true"

- import_tasks: deploy.yml

- import_tasks: configure-etcd-leave.yml
  when:
    - etcd == "true"

- import_tasks: post-conf-master-bootstrap.yml
  tags: bootstrap
  when:
    - master == "true"

- import_tasks: post-conf-master-bootstrap-autoscaler.yml
  tags: bootstrap
  when:
    - master == "true"
    - automium_autoscaler_kubeconfig != ""

- import_tasks: post-conf-master-etcd.yml
  when:
    - etcd == "true" or master == "true"

- import_tasks: enable-autoscaler.yml
  tags: others
  when:
    - automium_autoscaler_kubeconfig != ""

- import_tasks: configure-master-node-leave.yml
  tags: others
  when:
    - master == "true" or node == "true"

- import_tasks: post-conf-node.yml
  when:
    - node == "true"
